---
secrets:
  eso:
    vault:
      server: http://172.18.0.5:8200
      namespace: ""
      auth:
        kubernetes:
          mountPath: tap-iterate
          role: tap-iterate--tanzu-sync-secrets
    remote_refs:
      sync_git:
        basic_auth:
          username:
            key: secret/dev/tap-iterate/tanzu-sync/git-credentials
            property: username
          password:
            key: secret/dev/tap-iterate/tanzu-sync/git-credentials
            property: password
      install_registry_dockerconfig:
        dockerconfigjson:
          key: secret/dev/tap-iterate/tanzu-sync/install-registry-dockerconfig
          property: dockerconfigjson
