tap_install:
  package_repository:
    oci_repository: tap-sm-docker-dev-local.dmz.packages.broadcom.com/1.12.6-build.13/tanzu-application-platform/tap-packages
  version:
    package_repo_bundle_tag: 1.12.6-build.13
    package_version: 1.12.6-build.13
  values:
    ceip_policy_disclosed: true
    profile: iterate
    shared:
      ingress_domain: "tap-iterate.local"
